redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"

postgres:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  ports:
    - "5432:5432"

mail:
 restart: always
 image: tianon/exim4
 expose:
    - "25"
